variable "cluster_name" {}
variable "vpc_cidr" {}
variable "private_subnets_cidr1" {}
variable "private_subnets_cidr2" {}
variable "private_subnets_cidr3" {}
variable "public_subnet_cidr1" {}
variable "public_subnet_cidr2" {}
variable "public_subnet_cidr3" {}

variable "ami_type" {}
variable "node_group1_name" {}
variable "node_group1_instance_type" {}
variable "node_group1_min_size" {}
variable "node_group1_max_size" {}
variable "node_group1_desired_size" {}
variable "node_group2_name" {}
variable "node_group2_instance_type" {}
variable "node_group2_min_size" {}
variable "node_group2_max_size" {}
variable "node_group2_desired_size" {}
