apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - name: nginx-app
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "0.5"
      volumeMounts:
        - mountPath: "/data"
          name: ebs-storage
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: ebs-pvc
